[package]
name = "bits_n_bite"
version = "0.1.0"
authors = ["cobyeast <cobyeastwood@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-session = "0.4.0"